### ISSUE TITLE
css for nicer looking links

### ISSUE THREAD

**Issue by AliciaSchep** [ijlyttle/altair#20]
Looking at example plots in the Altair (python) documentation, the links at the bottom are nicely spaced out:

![altair_py_example](https://user-images.githubusercontent.com/6809790/38848172-8c924934-41ba-11e8-8210-8c30ac38a839.png)

Looking at the similar plot in the altair (r) documentation:

![altair_r_example](https://user-images.githubusercontent.com/6809790/38848189-b2bca3fc-41ba-11e8-9f9d-d704c7fda9a8.png)

The links are ugly/overlapping :frowning_face:  (imo)

I think some simple css could fix this issue -- happy to put some together (& try to figure out what the frontend for the Altair documentation is using) and make a PR but figured best to raise an issue first & see if there would be support for that!

**Comment by ijlyttle** [comment]
I wholeheartedly agree and would love a PR. Every time I render a chart, I think the same thing to myself, but then get distracted by whatever I was trying to get working in the first place 😬

I think such a PR would be related to, but independent of #16.
