### ISSUE TITLE
Variable names may not contain dots!

### ISSUE THREAD

**Issue by ijlyttle** [ijlyttle/altair#3]
`iris` - as is - fails.

Just to note for now.

**Comment by AliciaSchep** [comment]
Perhaps this package could include a helper function to strip column names of dots?  Or the documentation could recommend a method from another package, like [janitor](https://github.com/sfirke/janitor)'s  `janitor::clean_names`?  

If the package were to include some R constructors at some point, those constructors could do a check for "." in names.

**Comment by ijlyttle** [comment]
Followup - it almost works. It took me a while to notice the axes:

![visualization 1](https://user-images.githubusercontent.com/2800934/39090442-1140e40e-45a5-11e8-83c6-e3f3a6393fd5.png)

Maybe this could be an Altair or Vega issue? I'll have to poke around some more.

**Comment by AliciaSchep** [comment]
Neat! I agree that documenting the work-around seems good enough for this issue.  

Using "\\" to escape the period also seems to "work", although leaves one "\" in the axis name.  Based on the result of looking at & opening up the spec Altair creates in vega editor, I think this is an issue on the part of vega and not Altair

**Comment by ijlyttle** [comment]
This should be a part of #31

**Comment by ijlyttle** [comment]
included in #37
