### ISSUE TITLE
how to synchronize dependencies with Altair?

### ISSUE THREAD

**Issue by AliciaSchep** [ijlyttle/altair#33]
Over in Altair repo the Altair package has been [updated to use newer version of js libraries](https://github.com/altair-viz/altair/pull/786).  How does/will this package attempt to stay up-to-date with versions used by Altair?

**Comment by AliciaSchep** [comment]
Related question: Will altair require a specific version of Altair?

**Comment by ijlyttle** [comment]
I have been wrestling with this question for a while, so I will be very happy for your thoughts - especially as I am somewhat unsure of my reasoning.

I *think* an essential question is how to we keep the installation-method for the Python package, `install_altair()`, current with the version of the js libraries in `inst/htmlwidgets`?  

For Altair, there will be three ways to install:

- [pure Conda](https://anaconda.org/conda-forge/altair), which should be available in the near future for v2
- [PyPi](https://pypi.org/project/altair/), which is being used also for release-candidates. In the `new-docs` branch, the `install_altair()` function currently installs into Conda using pip for `altair==2.0.0rc2`
- [directly from github](https://altair-viz.github.io/getting_started/installation.html#development-install) (which I have not tried yet using `reticulate::install_conda()`).

By hard-coding our `install_altair()` function, we could specify which way is to be used, giving us a mechanism to support a specific version. We could have a `check_altair()` function to see if the installed version matches the required version, but I don't know if we could have it run `.onLoad()` for fear of rendering moot the `delay_load`. 

As you point out, each of these Altair versions will be tied to specific versions of the JS libraries. Perhaps, as a part of our development process, we should make sure that the JS libraries in `inst/htmlwidgets` comports with the Altair JS versions, according to the Altair version installed by `install_altair()`.

This leads to another question about how we manage the development process (I still need to write that contribution guide...).

As a first idea, and I am toying with this now, perhaps we can use three main types of branches:

- `master` uses a released Conda version (uses release candidate from PyPi only until V2 is officially released)
- `devel` can use a release candidate from PyPi
- `<feature-branch>` can use a github version of Altair

I'm sure you recognize this from gitflow; I am trying to see what adaptations can be made so we can incorporate a [dev version](http://pkgdown.r-lib.org/reference/build_site.html#development-mode) of the documentation in pkgdown.

What do you think?

**Comment by ijlyttle** [comment]
oooh, I like these ideas... will think on this today!

**Comment by ijlyttle** [comment]
Just to build off of your ideas:

Hard-coding an option in `onLoad()`,

```r
.onLoad <- function(libname, pkgname) {

  options(altair.python.supported.version = "2.0.0rc2")

  alt <<- reticulate::import(
    "altair",
     delay_load = list(
       on_load = on_altair_load,
       on_error = on_altair_error
     )
  )
}
```

could `check_altair()` look something like this?

```r
check_altair <- function() {

  # check that Altair is available
  has_altair <- reticulate::py_module_available("altair")
  assertthat::assert_that(has_altair, msg = "Python package Altair not found")

  # check that version is supported
  version_installed <- alt$`__version__`
  version_supported <- getOption("altair.python.supported.version")
  if (!identical(version_altair, version_supported)) {
    warning("informative warning goes here")
  }
}
```

could we suggest a call to `reticulate::py_config()` in `on_altair_error()`? or even call it?

---

Restating my [comment](https://github.com/ijlyttle/altair/issues/34#issuecomment-386273905) from the other issue, I think that it will be our responsibility to ensure the versions of the JS libraries we supply in `inst/htmlwidgets` work with the Altair versions we support in `"altair.python.supported.version"`.

It's too bad that `alt$VEGALITE_VERSION` and `alt$VEGAEMBED_VERSION` might not be as useful as we hoped...

**Comment by AliciaSchep** [comment]
That seems like a reasonable approach!  I'm not sure if the `has_altair` call in `check_altair` is necessary  though-- if that is being used as `on_load` in `import`, I think it would only get called if `altair` was successfully loaded.  

Calling or suggesting `reticulate::py_config()` in `on_altair_error()` sounds like a good idea!

I agree that making sure the JS libraries work for the supported Altair version is the responsibility of this package and its maintainers. 

One thought about the warning/check for altair version-- perhaps there should be an escalation based on how off the version is:

* Patch version difference only leads to message 
* Minor version difference leads to warning
* Major version difference leads to error (versions < 2 for example will definitely be very problematic)

**Comment by ijlyttle** [comment]
You're right! The first bit is redundant - I should have seen that... thanks!

I like the escalation idea!
