### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by ijlyttle** [ijlyttle/altair#4]
Everybody likes tooltips...

**Comment by AliciaSchep** [comment]
Doing

```r
plot <- 
  alt$Chart(
    r_to_py(mtcars)
  )$mark_point(
  )$encode(
    x = "mpg:Q",
    y = "hp:Q",
    color = "cyl:N", 
    tooltip = "hp:Q"
  )
```
Already provides a simple tooltip with the 'hp' value.  However, it doesn't seem to show up in rstudio viewer -- only worked when I opened it up in my browser.

Would you want to incorporate the vega-tooltip plugin into the htmlwidget?  (what vegalite r package does).

**Comment by ijlyttle** [comment]
Yes, absolutely!
